--
-- PostgreSQL database dump
--

\restrict xMVffIskuXGB8ouokmH9vm5hE6IDwqRdxUVzAMEfmXsazSDWEe7sg7D97REZtsA

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

-- Started on 2025-11-10 20:27:24

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 255 (class 1259 OID 17870)
-- Name: account_emailaddress; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.account_emailaddress (
    id integer NOT NULL,
    email character varying(254) NOT NULL,
    verified boolean NOT NULL,
    "primary" boolean NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.account_emailaddress OWNER TO techspark_user;

--
-- TOC entry 254 (class 1259 OID 17869)
-- Name: account_emailaddress_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.account_emailaddress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_emailaddress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 257 (class 1259 OID 17883)
-- Name: account_emailconfirmation; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.account_emailconfirmation (
    id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    sent timestamp with time zone,
    key character varying(64) NOT NULL,
    email_address_id integer NOT NULL
);


ALTER TABLE public.account_emailconfirmation OWNER TO techspark_user;

--
-- TOC entry 256 (class 1259 OID 17882)
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.account_emailconfirmation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_emailconfirmation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16943)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO techspark_user;

--
-- TOC entry 225 (class 1259 OID 16942)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16953)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO techspark_user;

--
-- TOC entry 227 (class 1259 OID 16952)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16933)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO techspark_user;

--
-- TOC entry 223 (class 1259 OID 16932)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16962)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO techspark_user;

--
-- TOC entry 232 (class 1259 OID 16981)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO techspark_user;

--
-- TOC entry 231 (class 1259 OID 16980)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16961)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16990)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO techspark_user;

--
-- TOC entry 233 (class 1259 OID 16989)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 17051)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO techspark_user;

--
-- TOC entry 235 (class 1259 OID 17050)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16921)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO techspark_user;

--
-- TOC entry 221 (class 1259 OID 16920)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16909)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO techspark_user;

--
-- TOC entry 219 (class 1259 OID 16908)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 17091)
-- Name: django_session; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO techspark_user;

--
-- TOC entry 259 (class 1259 OID 17920)
-- Name: django_site; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.django_site (
    id integer NOT NULL,
    domain character varying(100) NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.django_site OWNER TO techspark_user;

--
-- TOC entry 258 (class 1259 OID 17919)
-- Name: django_site_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.django_site ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 261 (class 1259 OID 17932)
-- Name: socialaccount_socialaccount; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.socialaccount_socialaccount (
    id integer NOT NULL,
    provider character varying(200) NOT NULL,
    uid character varying(191) NOT NULL,
    last_login timestamp with time zone NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    extra_data jsonb NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.socialaccount_socialaccount OWNER TO techspark_user;

--
-- TOC entry 260 (class 1259 OID 17931)
-- Name: socialaccount_socialaccount_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.socialaccount_socialaccount ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialaccount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 263 (class 1259 OID 17947)
-- Name: socialaccount_socialapp; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.socialaccount_socialapp (
    id integer NOT NULL,
    provider character varying(30) NOT NULL,
    name character varying(40) NOT NULL,
    client_id character varying(191) NOT NULL,
    secret character varying(191) NOT NULL,
    key character varying(191) NOT NULL,
    provider_id character varying(200) NOT NULL,
    settings jsonb NOT NULL
);


ALTER TABLE public.socialaccount_socialapp OWNER TO techspark_user;

--
-- TOC entry 262 (class 1259 OID 17946)
-- Name: socialaccount_socialapp_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.socialaccount_socialapp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialapp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 265 (class 1259 OID 17959)
-- Name: socialaccount_socialapp_sites; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.socialaccount_socialapp_sites (
    id bigint NOT NULL,
    socialapp_id integer NOT NULL,
    site_id integer NOT NULL
);


ALTER TABLE public.socialaccount_socialapp_sites OWNER TO techspark_user;

--
-- TOC entry 264 (class 1259 OID 17958)
-- Name: socialaccount_socialapp_sites_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.socialaccount_socialapp_sites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialapp_sites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 267 (class 1259 OID 17968)
-- Name: socialaccount_socialtoken; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.socialaccount_socialtoken (
    id integer NOT NULL,
    token text NOT NULL,
    token_secret text NOT NULL,
    expires_at timestamp with time zone,
    account_id integer NOT NULL,
    app_id integer
);


ALTER TABLE public.socialaccount_socialtoken OWNER TO techspark_user;

--
-- TOC entry 266 (class 1259 OID 17967)
-- Name: socialaccount_socialtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.socialaccount_socialtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 17765)
-- Name: techspark_address; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.techspark_address (
    id bigint NOT NULL,
    full_name character varying(150) NOT NULL,
    phone character varying(15) NOT NULL,
    street_address character varying(255) NOT NULL,
    city character varying(100) NOT NULL,
    province character varying(100) NOT NULL,
    postal_code character varying(10) NOT NULL,
    is_default boolean NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.techspark_address OWNER TO techspark_user;

--
-- TOC entry 246 (class 1259 OID 17764)
-- Name: techspark_address_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.techspark_address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.techspark_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 17120)
-- Name: techspark_cart; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.techspark_cart (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.techspark_cart OWNER TO techspark_user;

--
-- TOC entry 240 (class 1259 OID 17119)
-- Name: techspark_cart_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.techspark_cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.techspark_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 17131)
-- Name: techspark_cartitem; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.techspark_cartitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    cart_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT techspark_cartitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.techspark_cartitem OWNER TO techspark_user;

--
-- TOC entry 242 (class 1259 OID 17130)
-- Name: techspark_cartitem_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.techspark_cartitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.techspark_cartitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 17748)
-- Name: techspark_category; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.techspark_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.techspark_category OWNER TO techspark_user;

--
-- TOC entry 244 (class 1259 OID 17747)
-- Name: techspark_category_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.techspark_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.techspark_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 17782)
-- Name: techspark_order; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.techspark_order (
    id bigint NOT NULL,
    full_name character varying(150) NOT NULL,
    phone character varying(15) NOT NULL,
    shipping_address text NOT NULL,
    total_price numeric(10,0) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    is_paid boolean NOT NULL,
    user_id integer,
    payment_method character varying(10) NOT NULL,
    status character varying(20) NOT NULL
);


ALTER TABLE public.techspark_order OWNER TO techspark_user;

--
-- TOC entry 248 (class 1259 OID 17781)
-- Name: techspark_order_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.techspark_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.techspark_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 17797)
-- Name: techspark_orderitem; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.techspark_orderitem (
    id bigint NOT NULL,
    product_name character varying(200) NOT NULL,
    product_price numeric(10,0) NOT NULL,
    quantity integer NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint,
    CONSTRAINT techspark_orderitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.techspark_orderitem OWNER TO techspark_user;

--
-- TOC entry 250 (class 1259 OID 17796)
-- Name: techspark_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.techspark_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.techspark_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 17104)
-- Name: techspark_product; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.techspark_product (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    description text NOT NULL,
    price numeric(10,0) NOT NULL,
    image_url character varying(1000) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    stock integer NOT NULL,
    category_id bigint
);


ALTER TABLE public.techspark_product OWNER TO techspark_user;

--
-- TOC entry 238 (class 1259 OID 17103)
-- Name: techspark_product_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.techspark_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.techspark_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 253 (class 1259 OID 17836)
-- Name: techspark_rating; Type: TABLE; Schema: public; Owner: techspark_user
--

CREATE TABLE public.techspark_rating (
    id bigint NOT NULL,
    rating integer NOT NULL,
    review_text text,
    created_at timestamp with time zone NOT NULL,
    order_item_id bigint NOT NULL,
    product_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.techspark_rating OWNER TO techspark_user;

--
-- TOC entry 252 (class 1259 OID 17835)
-- Name: techspark_rating_id_seq; Type: SEQUENCE; Schema: public; Owner: techspark_user
--

ALTER TABLE public.techspark_rating ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.techspark_rating_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5306 (class 0 OID 17870)
-- Dependencies: 255
-- Data for Name: account_emailaddress; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.account_emailaddress (id, email, verified, "primary", user_id) FROM stdin;
1	riskirahmattillah19@gmail.com	t	t	7
\.


--
-- TOC entry 5308 (class 0 OID 17883)
-- Dependencies: 257
-- Data for Name: account_emailconfirmation; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.account_emailconfirmation (id, created, sent, key, email_address_id) FROM stdin;
\.


--
-- TOC entry 5277 (class 0 OID 16943)
-- Dependencies: 226
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- TOC entry 5279 (class 0 OID 16953)
-- Dependencies: 228
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5275 (class 0 OID 16933)
-- Dependencies: 224
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add product	7	add_product
26	Can change product	7	change_product
27	Can delete product	7	delete_product
28	Can view product	7	view_product
29	Can add cart	8	add_cart
30	Can change cart	8	change_cart
31	Can delete cart	8	delete_cart
32	Can view cart	8	view_cart
33	Can add cart item	9	add_cartitem
34	Can change cart item	9	change_cartitem
35	Can delete cart item	9	delete_cartitem
36	Can view cart item	9	view_cartitem
37	Can add category	10	add_category
38	Can change category	10	change_category
39	Can delete category	10	delete_category
40	Can view category	10	view_category
41	Can add order	11	add_order
42	Can change order	11	change_order
43	Can delete order	11	delete_order
44	Can view order	11	view_order
45	Can add address	12	add_address
46	Can change address	12	change_address
47	Can delete address	12	delete_address
48	Can view address	12	view_address
49	Can add order item	13	add_orderitem
50	Can change order item	13	change_orderitem
51	Can delete order item	13	delete_orderitem
52	Can view order item	13	view_orderitem
53	Can add rating	14	add_rating
54	Can change rating	14	change_rating
55	Can delete rating	14	delete_rating
56	Can view rating	14	view_rating
57	Can add site	15	add_site
58	Can change site	15	change_site
59	Can delete site	15	delete_site
60	Can view site	15	view_site
61	Can add email address	16	add_emailaddress
62	Can change email address	16	change_emailaddress
63	Can delete email address	16	delete_emailaddress
64	Can view email address	16	view_emailaddress
65	Can add email confirmation	17	add_emailconfirmation
66	Can change email confirmation	17	change_emailconfirmation
67	Can delete email confirmation	17	delete_emailconfirmation
68	Can view email confirmation	17	view_emailconfirmation
69	Can add social account	18	add_socialaccount
70	Can change social account	18	change_socialaccount
71	Can delete social account	18	delete_socialaccount
72	Can view social account	18	view_socialaccount
73	Can add social application	19	add_socialapp
74	Can change social application	19	change_socialapp
75	Can delete social application	19	delete_socialapp
76	Can view social application	19	view_socialapp
77	Can add social application token	20	add_socialtoken
78	Can change social application token	20	change_socialtoken
79	Can delete social application token	20	delete_socialtoken
80	Can view social application token	20	view_socialtoken
\.


--
-- TOC entry 5281 (class 0 OID 16962)
-- Dependencies: 230
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1000000$trMmuiHguQaPcJfgtBh6zK$bUtSGLYclMe7W6g5H/gWtjagx9D4HtIaDOy5FBO2x4k=	\N	t	rahmat2341				t	t	2025-10-23 20:41:52.628548+07
5	pbkdf2_sha256$1000000$Qq6kV33fcKc4wwRmPPXSuR$o6g9kUAuQJtmysGjg6s7HQR1vnj/Q7ZAqp+zyypL69w=	2025-11-05 15:47:09.557206+07	f	dhava@gmail.com	dhava		dhava@gmail.com	f	t	2025-10-30 10:06:01.179483+07
2	pbkdf2_sha256$1000000$1PfnWIyn0ipNiAvcV4Nk5j$ttvq5sDwZ48NiKMXCdYB48W90YU0HL4hDbmfH77Incw=	2025-11-07 11:16:59.725672+07	f	riski@gmail.com	riski12		riski@gmail.com	f	t	2025-10-29 20:20:10.344063+07
7	!eFy3qXQbbM0YonII5tZjS5dwku1zQZUeQ3BPCd3J	2025-11-09 17:30:49.074417+07	f	iiky	IIKY		riskirahmattillah19@gmail.com	f	t	2025-11-09 17:30:48.911656+07
3	pbkdf2_sha256$1000000$RAcqfGMHva6HBdCnFrINQJ$6YkRUj+Wqha8HVcEUhLgIAGmSDZBdk6V3I4WyphNJPk=	2025-11-10 19:41:49.739283+07	t	admin				t	t	2025-10-29 23:24:38.754948+07
6	pbkdf2_sha256$1000000$LMRWS2ownYEI7nlhn0kvcT$BcV/fs4c6fe+tw5cALruPA8D01moTHKvN1m82OMLjiE=	2025-11-10 19:42:11.02708+07	f	rahmat@gmail.com	rahmat12		rahmat@gmail.com	f	t	2025-11-07 11:25:10.478692+07
\.


--
-- TOC entry 5283 (class 0 OID 16981)
-- Dependencies: 232
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- TOC entry 5285 (class 0 OID 16990)
-- Dependencies: 234
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5287 (class 0 OID 17051)
-- Dependencies: 236
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-11-03 16:20:41.175575+07	1	Laptops	1	[{"added": {}}]	10	3
2	2025-11-03 16:21:07.007387+07	2	Handphones	1	[{"added": {}}]	10	3
3	2025-11-03 16:21:36.907533+07	3	Headsets	1	[{"added": {}}]	10	3
4	2025-11-03 16:22:02.42798+07	4	Camera	1	[{"added": {}}]	10	3
5	2025-11-08 22:06:47.421656+07	1	127.0.0.1:8000	2	[{"changed": {"fields": ["Domain name", "Display name"]}}]	15	3
6	2025-11-08 22:09:45.842173+07	1	Google Auth	1	[{"added": {}}]	19	3
7	2025-11-09 18:35:31.773745+07	2	Facebook Auth	1	[{"added": {}}]	19	3
\.


--
-- TOC entry 5273 (class 0 OID 16921)
-- Dependencies: 222
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	techspark	product
8	techspark	cart
9	techspark	cartitem
10	techspark	category
11	techspark	order
12	techspark	address
13	techspark	orderitem
14	techspark	rating
15	sites	site
16	account	emailaddress
17	account	emailconfirmation
18	socialaccount	socialaccount
19	socialaccount	socialapp
20	socialaccount	socialtoken
\.


--
-- TOC entry 5271 (class 0 OID 16909)
-- Dependencies: 220
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-10-23 20:41:14.53899+07
2	auth	0001_initial	2025-10-23 20:41:14.664756+07
3	admin	0001_initial	2025-10-23 20:41:14.718366+07
4	admin	0002_logentry_remove_auto_add	2025-10-23 20:41:14.736628+07
5	admin	0003_logentry_add_action_flag_choices	2025-10-23 20:41:14.74653+07
6	contenttypes	0002_remove_content_type_name	2025-10-23 20:41:14.771909+07
7	auth	0002_alter_permission_name_max_length	2025-10-23 20:41:14.789632+07
8	auth	0003_alter_user_email_max_length	2025-10-23 20:41:14.808742+07
9	auth	0004_alter_user_username_opts	2025-10-23 20:41:14.822518+07
10	auth	0005_alter_user_last_login_null	2025-10-23 20:41:14.835013+07
11	auth	0006_require_contenttypes_0002	2025-10-23 20:41:14.83609+07
12	auth	0007_alter_validators_add_error_messages	2025-10-23 20:41:14.846583+07
13	auth	0008_alter_user_username_max_length	2025-10-23 20:41:14.860798+07
14	auth	0009_alter_user_last_name_max_length	2025-10-23 20:41:14.866982+07
15	auth	0010_alter_group_name_max_length	2025-10-23 20:41:14.878924+07
16	auth	0011_update_proxy_permissions	2025-10-23 20:41:14.886204+07
17	auth	0012_alter_user_first_name_max_length	2025-10-23 20:41:14.898207+07
18	sessions	0001_initial	2025-10-23 20:41:14.923017+07
19	techspark	0001_initial	2025-10-30 00:05:39.57031+07
20	techspark	0002_product_stock	2025-10-31 22:05:44.835254+07
21	techspark	0003_cart_cartitem	2025-10-31 22:18:47.038358+07
22	techspark	0004_category	2025-11-03 16:10:34.446316+07
23	techspark	0005_product_category	2025-11-03 16:55:15.539136+07
24	techspark	0006_address_order_orderitem	2025-11-03 17:55:40.768162+07
25	techspark	0007_order_payment_method	2025-11-03 20:08:15.400077+07
26	techspark	0008_order_status_orderitem_product_and_more	2025-11-03 21:17:25.312858+07
27	techspark	0009_alter_order_payment_method	2025-11-04 20:21:57.787057+07
28	account	0001_initial	2025-11-08 21:41:10.283617+07
29	account	0002_email_max_length	2025-11-08 21:41:10.326222+07
30	account	0003_alter_emailaddress_create_unique_verified_email	2025-11-08 21:41:10.384512+07
31	account	0004_alter_emailaddress_drop_unique_email	2025-11-08 21:41:10.498837+07
32	account	0005_emailaddress_idx_upper_email	2025-11-08 21:41:10.53013+07
33	account	0006_emailaddress_lower	2025-11-08 21:41:10.588113+07
34	account	0007_emailaddress_idx_email	2025-11-08 21:41:10.645681+07
35	account	0008_emailaddress_unique_primary_email_fixup	2025-11-08 21:41:10.694322+07
36	account	0009_emailaddress_unique_primary_email	2025-11-08 21:41:10.728962+07
37	sites	0001_initial	2025-11-08 21:41:10.756427+07
38	sites	0002_alter_domain_unique	2025-11-08 21:41:10.779932+07
39	socialaccount	0001_initial	2025-11-08 21:41:11.014898+07
40	socialaccount	0002_token_max_lengths	2025-11-08 21:41:11.082617+07
41	socialaccount	0003_extra_data_default_dict	2025-11-08 21:41:11.122654+07
42	socialaccount	0004_app_provider_id_settings	2025-11-08 21:41:11.194738+07
43	socialaccount	0005_socialtoken_nullable_app	2025-11-08 21:41:11.252001+07
44	socialaccount	0006_alter_socialaccount_extra_data	2025-11-08 21:41:11.327094+07
\.


--
-- TOC entry 5288 (class 0 OID 17091)
-- Dependencies: 237
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
yxpmcadhrahn24bzgzbmmigbz0emmfzp	.eJxVjEEOwiAQRe_C2hAoAlOX7nsGMsNMpWpKUtqV8e7apAvd_vfef6mE21rS1mRJE6uLCur0uxHmh8w74DvOt6pznddlIr0r-qBND5XleT3cv4OCrXxrE1jEWQR0LGfX9b4P2VoAQxFGHwmMZ8bos42mI7AUwNgoQDF7M_bq_QHWPTdP:1vIRDn:DIXCxUww0j4kaXjZUUuubmgOdyzxMkmtdfbn6_OCdiU	2025-11-24 19:42:11.03242+07
u1igmniwqirl5gsowf2b4lqb6yvi2kcs	.eJxVjEEOwiAQRe_C2hCYKaW4dO8ZyDCAVA0kpV0Z765NutDtf-_9l_C0rcVvPS1-juIsUJx-t0D8SHUH8U711iS3ui5zkLsiD9rltcX0vBzu30GhXr61zVNmBhxHo9FaYw1l0MwGnIMhoWKtsrLJIRG6qEJOAxkAYqNcjpN4fwDPhTej:1vErvB:a5gyK8Ic8C7PgU6n6_8SjWtd-Hqs1FwTDmB0AR-XJRs	2025-11-14 23:24:13.856095+07
\.


--
-- TOC entry 5310 (class 0 OID 17920)
-- Dependencies: 259
-- Data for Name: django_site; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.django_site (id, domain, name) FROM stdin;
1	127.0.0.1:8000	TechSpark
\.


--
-- TOC entry 5312 (class 0 OID 17932)
-- Dependencies: 261
-- Data for Name: socialaccount_socialaccount; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.socialaccount_socialaccount (id, provider, uid, last_login, date_joined, extra_data, user_id) FROM stdin;
1	google	111869501291891420875	2025-11-09 17:30:49.025296+07	2025-11-09 17:30:49.025332+07	{"aud": "18547659537-gkb51i5v3v22jjrhv2hnnssdkofns0c7.apps.googleusercontent.com", "azp": "18547659537-gkb51i5v3v22jjrhv2hnnssdkofns0c7.apps.googleusercontent.com", "exp": 1762687848, "iat": 1762684248, "iss": "https://accounts.google.com", "sub": "111869501291891420875", "name": "IIKY", "email": "riskirahmattillah19@gmail.com", "at_hash": "8hWxBd9UxvX4AxQTRt1KIg", "picture": "https://lh3.googleusercontent.com/a/ACg8ocKIXXQDdAIh2O2_iE6uBe6J7f0cM6tAiQQJmnsq15FhZ1J3xNNHUg=s96-c", "given_name": "IIKY", "email_verified": true}	7
\.


--
-- TOC entry 5314 (class 0 OID 17947)
-- Dependencies: 263
-- Data for Name: socialaccount_socialapp; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.socialaccount_socialapp (id, provider, name, client_id, secret, key, provider_id, settings) FROM stdin;
1	google	Google Auth	18547659537-gkb51i5v3v22jjrhv2hnnssdkofns0c7.apps.googleusercontent.com	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			{}
2	facebook	Facebook Auth	1657156835669661	b55524593ee6858842197c59fa63e0c0			{}
\.


--
-- TOC entry 5316 (class 0 OID 17959)
-- Dependencies: 265
-- Data for Name: socialaccount_socialapp_sites; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.socialaccount_socialapp_sites (id, socialapp_id, site_id) FROM stdin;
1	1	1
2	2	1
\.


--
-- TOC entry 5318 (class 0 OID 17968)
-- Dependencies: 267
-- Data for Name: socialaccount_socialtoken; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.socialaccount_socialtoken (id, token, token_secret, expires_at, account_id, app_id) FROM stdin;
\.


--
-- TOC entry 5298 (class 0 OID 17765)
-- Dependencies: 247
-- Data for Name: techspark_address; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.techspark_address (id, full_name, phone, street_address, city, province, postal_code, is_default, user_id) FROM stdin;
1	Riski Rahmattillah Pratama	5655456124	awhfafjahdhgaf	Kabupaten Madiun	Jawa Timur	63112	t	2
2	Riski Rahmattillah Pratama	5655456124	awhfafjahdhgaf	Kabupaten Madiun	Jawa Timur	63112	f	2
3	Riski Rahmattillah Pratama	5655456124	awhfafjahdhgaf	Kabupaten Madiun	Jawa Timur	63112	f	2
4	Riski Rahmattillah Pratama	5655456124	awhfafjahdhgaf	Kabupaten Madiun	Jawa Timur	63112	f	2
5	Riski Rahmattillah Pratama	5655456124	awhfafjahdhgaf	Kabupaten Madiun	Jawa Timur	63112	f	2
6	sadaw	546465456	adadaw	asdqad	adqw	4654	t	5
7	rahmat	65656465	Jln. Pahlawan	Kota. Madiun	Jawa Timur	63111	t	6
\.


--
-- TOC entry 5292 (class 0 OID 17120)
-- Dependencies: 241
-- Data for Name: techspark_cart; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.techspark_cart (id, created_at, user_id) FROM stdin;
1	2025-10-31 22:23:29.469701+07	2
2	2025-11-04 19:42:14.967431+07	3
3	2025-11-04 21:00:51.608949+07	5
4	2025-11-08 21:10:31.876795+07	6
\.


--
-- TOC entry 5294 (class 0 OID 17131)
-- Dependencies: 243
-- Data for Name: techspark_cartitem; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.techspark_cartitem (id, quantity, cart_id, product_id) FROM stdin;
7	1	2	6
8	1	2	4
\.


--
-- TOC entry 5296 (class 0 OID 17748)
-- Dependencies: 245
-- Data for Name: techspark_category; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.techspark_category (id, name) FROM stdin;
4	Camera
3	Audio
1	Laptop
2	Smartphone
\.


--
-- TOC entry 5300 (class 0 OID 17782)
-- Dependencies: 249
-- Data for Name: techspark_order; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.techspark_order (id, full_name, phone, shipping_address, total_price, created_at, is_paid, user_id, payment_method, status) FROM stdin;
1	Riski Rahmattillah Pratama	5655456124	awhfafjahdhgaf, Kabupaten Madiun, Jawa Timur, 63112	68100000	2025-11-03 18:05:27.331162+07	f	2	cod	pending
2	Riski Rahmattillah Pratama	5655456124	awhfafjahdhgaf, Kabupaten Madiun, Jawa Timur, 63112	25700000	2025-11-03 18:06:20.056108+07	f	2	cod	pending
3	Riski Rahmattillah Pratama	5655456124	awhfafjahdhgaf, Kabupaten Madiun, Jawa Timur, 63112	6599000	2025-11-03 20:30:35.571323+07	f	2	qris	pending
5	Riski Rahmattillah Pratama	5655456124	awhfafjahdhgaf, Kabupaten Madiun, Jawa Timur, 63112	6599000	2025-11-04 20:02:57.781753+07	f	2	cod	completed
6	sadaw	546465456	adadaw, asdqad, adqw, 4654	6599000	2025-11-04 21:01:13.817661+07	f	5	qris	completed
4	Riski Rahmattillah Pratama	5655456124	awhfafjahdhgaf, Kabupaten Madiun, Jawa Timur, 63112	6599000	2025-11-03 20:32:17.721167+07	f	2	qris	processing
7	rahmat	65656465	Jln. Pahlawan, Kota. Madiun, Jawa Timur, 63111	6599000	2025-11-08 21:11:21.942536+07	f	6	cod	completed
\.


--
-- TOC entry 5302 (class 0 OID 17797)
-- Dependencies: 251
-- Data for Name: techspark_orderitem; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.techspark_orderitem (id, product_name, product_price, quantity, order_id, product_id) FROM stdin;
1	Samsung A56	6700000	5	1	\N
2	Galaxy S25 FE	8900000	1	1	\N
3	Panasonic LUMIX G9 II	25700000	1	1	\N
4	Panasonic LUMIX G9 II	25700000	1	2	\N
5	Sony WH-1000XM6	6599000	1	3	\N
6	Sony WH-1000XM6	6599000	1	4	\N
7	Sony WH-1000XM6	6599000	1	5	6
8	Sony WH-1000XM6	6599000	1	6	6
9	Sony WH-1000XM6	6599000	1	7	6
\.


--
-- TOC entry 5290 (class 0 OID 17104)
-- Dependencies: 239
-- Data for Name: techspark_product; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.techspark_product (id, name, description, price, image_url, created_at, stock, category_id) FROM stdin;
5	Panasonic LUMIX G9 II	Panasonic Lumix G9 II adalah kamera mirrorless Micro Four Thirds yang dirancang untuk foto dan video, menawarkan sensor 25,2 MP, sistem autofocus deteksi fase pertama pada seri G, dan stabilisasi gambar bodi 5 sumbu. Kamera ini unggul dalam kinerja hybrid dengan kemampuan merekam video 10-bit 4:2:2 hingga C4K/4K 60p dan fitur video canggih lainnya seperti Apple ProRes. Desainnya menyerupai Lumix S5 II dengan bodi yang tahan cipratan dan debu, serta dilengkapi dengan fitur seperti 75 fps continuous shooting, mode Handheld High-Res 100MP, dan konektivitas lengkap.	25700000	https://m.media-amazon.com/images/I/71NIwXkRhbL.jpg	2025-10-31 23:33:57.78372+07	3	4
4	LOQ 15IAX9	Lenovo LOQ 15IAX9 adalah laptop gaming entry-level yang ditenagai oleh prosesor Intel Core i5-12450HX dan grafis NVIDIA GeForce RTX 3050 6GB. Laptop ini memiliki layar 15,6 inci Full HD 144Hz dengan akurasi warna 100% sRGB, dilengkapi RAM 12GB DDR5 (dapat ditingkatkan) dan penyimpanan SSD 512GB. Fitur lainnya termasuk keyboard backlit putih, Wi-Fi 6, serta port yang lengkap, dan dilengkapi Windows 11 Home + Office Home & Student 2021.	12999000	https://pegastore.id/media/product/produk-1737700532.jpg	2025-10-31 23:29:03.465131+07	7	1
2	Samsung A56	Samsung A56 adalah smartphone mid-range premium dengan layar Super AMOLED 6,7 inci 120Hz, chipset Exynos 1580, dan kamera utama 50MP. Ponsel ini memiliki baterai 5000 mAh dengan pengisian cepat 45W, tahan air dan debu dengan sertifikasi IP67, serta menjalankan Android 15 dengan One UI 7. Peningkatan pada seri ini meliputi desain yang diperbarui, fitur AI seperti Circle to Search yang ditingkatkan, dan jaminan pembaruan software selama enam tahun.	6700000	https://media.suara.com/pictures/653x366/2024/08/06/12055-samsung-galaxy-a55-5g.jpg	2025-10-30 09:42:54.336603+07	5	2
1	Galaxy S25 FE	Samsung Galaxy S25 FE adalah ponsel kelas menengah atas (mid-range) yang menawarkan fitur kelas flagship dengan harga lebih terjangkau, ditenagai chipset Exynos 2400, dan memiliki performa kamera yang canggih berkat teknologi Galaxy AI. Ponsel ini memiliki layar Dynamic AMOLED 2X 6,7 inci 120Hz, RAM 8GB, penyimpanan internal hingga 256GB, dan baterai 4900mAh yang mendukung pengisian daya cepat 45W dan wireless charging 15W.	8900000	https://images.samsung.com/is/image/samsung/p6pim/id/feature/166449577/id-feature-slimmer--lighter-and-ready-to-impress-549079978?$FB_TYPE_K_JPG$	2025-10-30 09:22:41.356015+07	9	2
6	Sony WH-1000XM6	Sony WH-1000XM6 adalah headphone nirkabel dengan peredam bising canggih yang dilengkapi prosesor HD QN3, 12 mikrofon, dan fitur noise cancelling secara real-time untuk audio imersif. Headphone ini memiliki desain yang nyaman dengan bantalan memory foam yang empuk, headband lebih lebar, serta kemampuan lipat yang meningkatkan portabilitas. Fitur unggulannya meliputi koneksi multi-point yang mulus, daya tahan baterai hingga 30 jam (dengan ANC aktif), kualitas audio premium, dan kontrol intuitif melalui tombol serta aplikasi Sound Connect.	6599000	https://sony.scene7.com/is/image/sonyglobalsolutions/WH1000XM6_PrimaryTout_0pt-image01-d?$originalDimensions$&fmt=png-alpha	2025-10-31 23:38:11.550669+07	3	3
\.


--
-- TOC entry 5304 (class 0 OID 17836)
-- Dependencies: 253
-- Data for Name: techspark_rating; Type: TABLE DATA; Schema: public; Owner: techspark_user
--

COPY public.techspark_rating (id, rating, review_text, created_at, order_item_id, product_id, user_id) FROM stdin;
1	4	asdads	2025-11-04 20:58:43.374453+07	7	6	2
2	3	bagusss	2025-11-05 15:47:25.833447+07	8	6	5
3	4	mantap	2025-11-08 21:12:31.965612+07	9	6	6
\.


--
-- TOC entry 5324 (class 0 OID 0)
-- Dependencies: 254
-- Name: account_emailaddress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.account_emailaddress_id_seq', 1, true);


--
-- TOC entry 5325 (class 0 OID 0)
-- Dependencies: 256
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.account_emailconfirmation_id_seq', 1, false);


--
-- TOC entry 5326 (class 0 OID 0)
-- Dependencies: 225
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 5327 (class 0 OID 0)
-- Dependencies: 227
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 5328 (class 0 OID 0)
-- Dependencies: 223
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 80, true);


--
-- TOC entry 5329 (class 0 OID 0)
-- Dependencies: 231
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- TOC entry 5330 (class 0 OID 0)
-- Dependencies: 229
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 7, true);


--
-- TOC entry 5331 (class 0 OID 0)
-- Dependencies: 233
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- TOC entry 5332 (class 0 OID 0)
-- Dependencies: 235
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 7, true);


--
-- TOC entry 5333 (class 0 OID 0)
-- Dependencies: 221
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 20, true);


--
-- TOC entry 5334 (class 0 OID 0)
-- Dependencies: 219
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 44, true);


--
-- TOC entry 5335 (class 0 OID 0)
-- Dependencies: 258
-- Name: django_site_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.django_site_id_seq', 1, true);


--
-- TOC entry 5336 (class 0 OID 0)
-- Dependencies: 260
-- Name: socialaccount_socialaccount_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.socialaccount_socialaccount_id_seq', 1, true);


--
-- TOC entry 5337 (class 0 OID 0)
-- Dependencies: 262
-- Name: socialaccount_socialapp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.socialaccount_socialapp_id_seq', 2, true);


--
-- TOC entry 5338 (class 0 OID 0)
-- Dependencies: 264
-- Name: socialaccount_socialapp_sites_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.socialaccount_socialapp_sites_id_seq', 2, true);


--
-- TOC entry 5339 (class 0 OID 0)
-- Dependencies: 266
-- Name: socialaccount_socialtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.socialaccount_socialtoken_id_seq', 1, false);


--
-- TOC entry 5340 (class 0 OID 0)
-- Dependencies: 246
-- Name: techspark_address_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.techspark_address_id_seq', 7, true);


--
-- TOC entry 5341 (class 0 OID 0)
-- Dependencies: 240
-- Name: techspark_cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.techspark_cart_id_seq', 4, true);


--
-- TOC entry 5342 (class 0 OID 0)
-- Dependencies: 242
-- Name: techspark_cartitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.techspark_cartitem_id_seq', 11, true);


--
-- TOC entry 5343 (class 0 OID 0)
-- Dependencies: 244
-- Name: techspark_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.techspark_category_id_seq', 4, true);


--
-- TOC entry 5344 (class 0 OID 0)
-- Dependencies: 248
-- Name: techspark_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.techspark_order_id_seq', 7, true);


--
-- TOC entry 5345 (class 0 OID 0)
-- Dependencies: 250
-- Name: techspark_orderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.techspark_orderitem_id_seq', 9, true);


--
-- TOC entry 5346 (class 0 OID 0)
-- Dependencies: 238
-- Name: techspark_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.techspark_product_id_seq', 6, true);


--
-- TOC entry 5347 (class 0 OID 0)
-- Dependencies: 252
-- Name: techspark_rating_id_seq; Type: SEQUENCE SET; Schema: public; Owner: techspark_user
--

SELECT pg_catalog.setval('public.techspark_rating_id_seq', 3, true);


--
-- TOC entry 5060 (class 2606 OID 17879)
-- Name: account_emailaddress account_emailaddress_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_pkey PRIMARY KEY (id);


--
-- TOC entry 5063 (class 2606 OID 17913)
-- Name: account_emailaddress account_emailaddress_user_id_email_987c8728_uniq; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_email_987c8728_uniq UNIQUE (user_id, email);


--
-- TOC entry 5069 (class 2606 OID 17893)
-- Name: account_emailconfirmation account_emailconfirmation_key_key; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_key_key UNIQUE (key);


--
-- TOC entry 5071 (class 2606 OID 17891)
-- Name: account_emailconfirmation account_emailconfirmation_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_pkey PRIMARY KEY (id);


--
-- TOC entry 4991 (class 2606 OID 17087)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4996 (class 2606 OID 17008)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4999 (class 2606 OID 16960)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4993 (class 2606 OID 16949)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4986 (class 2606 OID 16999)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4988 (class 2606 OID 16941)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 5007 (class 2606 OID 16988)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 5010 (class 2606 OID 17023)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 5001 (class 2606 OID 16977)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 5013 (class 2606 OID 16997)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 5016 (class 2606 OID 17037)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 5004 (class 2606 OID 17080)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 5019 (class 2606 OID 17064)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4981 (class 2606 OID 16931)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4983 (class 2606 OID 16929)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4979 (class 2606 OID 16919)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 5023 (class 2606 OID 17100)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 5074 (class 2606 OID 17929)
-- Name: django_site django_site_domain_a2e37b91_uniq; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_domain_a2e37b91_uniq UNIQUE (domain);


--
-- TOC entry 5076 (class 2606 OID 17927)
-- Name: django_site django_site_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_pkey PRIMARY KEY (id);


--
-- TOC entry 5078 (class 2606 OID 17945)
-- Name: socialaccount_socialaccount socialaccount_socialaccount_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_pkey PRIMARY KEY (id);


--
-- TOC entry 5080 (class 2606 OID 18026)
-- Name: socialaccount_socialaccount socialaccount_socialaccount_provider_uid_fc810c6e_uniq; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_provider_uid_fc810c6e_uniq UNIQUE (provider, uid);


--
-- TOC entry 5085 (class 2606 OID 17991)
-- Name: socialaccount_socialapp_sites socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq UNIQUE (socialapp_id, site_id);


--
-- TOC entry 5083 (class 2606 OID 17957)
-- Name: socialaccount_socialapp socialaccount_socialapp_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.socialaccount_socialapp
    ADD CONSTRAINT socialaccount_socialapp_pkey PRIMARY KEY (id);


--
-- TOC entry 5087 (class 2606 OID 17966)
-- Name: socialaccount_socialapp_sites socialaccount_socialapp_sites_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_socialapp_sites_pkey PRIMARY KEY (id);


--
-- TOC entry 5093 (class 2606 OID 17981)
-- Name: socialaccount_socialtoken socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq UNIQUE (app_id, account_id);


--
-- TOC entry 5095 (class 2606 OID 17979)
-- Name: socialaccount_socialtoken socialaccount_socialtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_socialtoken_pkey PRIMARY KEY (id);


--
-- TOC entry 5042 (class 2606 OID 17780)
-- Name: techspark_address techspark_address_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.techspark_address
    ADD CONSTRAINT techspark_address_pkey PRIMARY KEY (id);


--
-- TOC entry 5029 (class 2606 OID 17127)
-- Name: techspark_cart techspark_cart_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.techspark_cart
    ADD CONSTRAINT techspark_cart_pkey PRIMARY KEY (id);


--
-- TOC entry 5031 (class 2606 OID 17129)
-- Name: techspark_cart techspark_cart_user_id_key; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.techspark_cart
    ADD CONSTRAINT techspark_cart_user_id_key UNIQUE (user_id);


--
-- TOC entry 5034 (class 2606 OID 17140)
-- Name: techspark_cartitem techspark_cartitem_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.techspark_cartitem
    ADD CONSTRAINT techspark_cartitem_pkey PRIMARY KEY (id);


--
-- TOC entry 5038 (class 2606 OID 17756)
-- Name: techspark_category techspark_category_name_key; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.techspark_category
    ADD CONSTRAINT techspark_category_name_key UNIQUE (name);


--
-- TOC entry 5040 (class 2606 OID 17754)
-- Name: techspark_category techspark_category_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.techspark_category
    ADD CONSTRAINT techspark_category_pkey PRIMARY KEY (id);


--
-- TOC entry 5045 (class 2606 OID 17795)
-- Name: techspark_order techspark_order_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.techspark_order
    ADD CONSTRAINT techspark_order_pkey PRIMARY KEY (id);


--
-- TOC entry 5049 (class 2606 OID 17807)
-- Name: techspark_orderitem techspark_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.techspark_orderitem
    ADD CONSTRAINT techspark_orderitem_pkey PRIMARY KEY (id);


--
-- TOC entry 5027 (class 2606 OID 17116)
-- Name: techspark_product techspark_product_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.techspark_product
    ADD CONSTRAINT techspark_product_pkey PRIMARY KEY (id);


--
-- TOC entry 5052 (class 2606 OID 17850)
-- Name: techspark_rating techspark_rating_order_item_id_key; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.techspark_rating
    ADD CONSTRAINT techspark_rating_order_item_id_key UNIQUE (order_item_id);


--
-- TOC entry 5054 (class 2606 OID 17848)
-- Name: techspark_rating techspark_rating_pkey; Type: CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.techspark_rating
    ADD CONSTRAINT techspark_rating_pkey PRIMARY KEY (id);


--
-- TOC entry 5057 (class 1259 OID 17916)
-- Name: account_emailaddress_email_03be32b2; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX account_emailaddress_email_03be32b2 ON public.account_emailaddress USING btree (email);


--
-- TOC entry 5058 (class 1259 OID 17917)
-- Name: account_emailaddress_email_03be32b2_like; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX account_emailaddress_email_03be32b2_like ON public.account_emailaddress USING btree (email varchar_pattern_ops);


--
-- TOC entry 5061 (class 1259 OID 17900)
-- Name: account_emailaddress_user_id_2c513194; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX account_emailaddress_user_id_2c513194 ON public.account_emailaddress USING btree (user_id);


--
-- TOC entry 5066 (class 1259 OID 17907)
-- Name: account_emailconfirmation_email_address_id_5b7f8c58; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX account_emailconfirmation_email_address_id_5b7f8c58 ON public.account_emailconfirmation USING btree (email_address_id);


--
-- TOC entry 5067 (class 1259 OID 17906)
-- Name: account_emailconfirmation_key_f43612bd_like; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX account_emailconfirmation_key_f43612bd_like ON public.account_emailconfirmation USING btree (key varchar_pattern_ops);


--
-- TOC entry 4989 (class 1259 OID 17088)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4994 (class 1259 OID 17019)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4997 (class 1259 OID 17020)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4984 (class 1259 OID 17005)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 5005 (class 1259 OID 17035)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 5008 (class 1259 OID 17034)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 5011 (class 1259 OID 17049)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 5014 (class 1259 OID 17048)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 5002 (class 1259 OID 17081)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 5017 (class 1259 OID 17075)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 5020 (class 1259 OID 17076)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 5021 (class 1259 OID 17102)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 5024 (class 1259 OID 17101)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 5072 (class 1259 OID 17930)
-- Name: django_site_domain_a2e37b91_like; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX django_site_domain_a2e37b91_like ON public.django_site USING btree (domain varchar_pattern_ops);


--
-- TOC entry 5081 (class 1259 OID 17989)
-- Name: socialaccount_socialaccount_user_id_8146e70c; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX socialaccount_socialaccount_user_id_8146e70c ON public.socialaccount_socialaccount USING btree (user_id);


--
-- TOC entry 5088 (class 1259 OID 18003)
-- Name: socialaccount_socialapp_sites_site_id_2579dee5; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX socialaccount_socialapp_sites_site_id_2579dee5 ON public.socialaccount_socialapp_sites USING btree (site_id);


--
-- TOC entry 5089 (class 1259 OID 18002)
-- Name: socialaccount_socialapp_sites_socialapp_id_97fb6e7d; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX socialaccount_socialapp_sites_socialapp_id_97fb6e7d ON public.socialaccount_socialapp_sites USING btree (socialapp_id);


--
-- TOC entry 5090 (class 1259 OID 18014)
-- Name: socialaccount_socialtoken_account_id_951f210e; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX socialaccount_socialtoken_account_id_951f210e ON public.socialaccount_socialtoken USING btree (account_id);


--
-- TOC entry 5091 (class 1259 OID 18015)
-- Name: socialaccount_socialtoken_app_id_636a42d7; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX socialaccount_socialtoken_app_id_636a42d7 ON public.socialaccount_socialtoken USING btree (app_id);


--
-- TOC entry 5043 (class 1259 OID 17813)
-- Name: techspark_address_user_id_c1ae140e; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX techspark_address_user_id_c1ae140e ON public.techspark_address USING btree (user_id);


--
-- TOC entry 5032 (class 1259 OID 17156)
-- Name: techspark_cartitem_cart_id_13d90c68; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX techspark_cartitem_cart_id_13d90c68 ON public.techspark_cartitem USING btree (cart_id);


--
-- TOC entry 5035 (class 1259 OID 17157)
-- Name: techspark_cartitem_product_id_19fe6174; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX techspark_cartitem_product_id_19fe6174 ON public.techspark_cartitem USING btree (product_id);


--
-- TOC entry 5036 (class 1259 OID 17757)
-- Name: techspark_category_name_b67f728b_like; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX techspark_category_name_b67f728b_like ON public.techspark_category USING btree (name varchar_pattern_ops);


--
-- TOC entry 5046 (class 1259 OID 17819)
-- Name: techspark_order_user_id_90dd486a; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX techspark_order_user_id_90dd486a ON public.techspark_order USING btree (user_id);


--
-- TOC entry 5047 (class 1259 OID 17825)
-- Name: techspark_orderitem_order_id_5383daf9; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX techspark_orderitem_order_id_5383daf9 ON public.techspark_orderitem USING btree (order_id);


--
-- TOC entry 5050 (class 1259 OID 17851)
-- Name: techspark_orderitem_product_id_3044a3cd; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX techspark_orderitem_product_id_3044a3cd ON public.techspark_orderitem USING btree (product_id);


--
-- TOC entry 5025 (class 1259 OID 17763)
-- Name: techspark_product_category_id_c43f7c8f; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX techspark_product_category_id_c43f7c8f ON public.techspark_product USING btree (category_id);


--
-- TOC entry 5055 (class 1259 OID 17867)
-- Name: techspark_rating_product_id_92278286; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX techspark_rating_product_id_92278286 ON public.techspark_rating USING btree (product_id);


--
-- TOC entry 5056 (class 1259 OID 17868)
-- Name: techspark_rating_user_id_e443a33c; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE INDEX techspark_rating_user_id_e443a33c ON public.techspark_rating USING btree (user_id);


--
-- TOC entry 5064 (class 1259 OID 17918)
-- Name: unique_primary_email; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE UNIQUE INDEX unique_primary_email ON public.account_emailaddress USING btree (user_id, "primary") WHERE "primary";


--
-- TOC entry 5065 (class 1259 OID 17914)
-- Name: unique_verified_email; Type: INDEX; Schema: public; Owner: techspark_user
--

CREATE UNIQUE INDEX unique_verified_email ON public.account_emailaddress USING btree (email) WHERE verified;


--
-- TOC entry 5116 (class 2606 OID 17894)
-- Name: account_emailaddress account_emailaddress_user_id_2c513194_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_2c513194_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5117 (class 2606 OID 17901)
-- Name: account_emailconfirmation account_emailconfirm_email_address_id_5b7f8c58_fk_account_e; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirm_email_address_id_5b7f8c58_fk_account_e FOREIGN KEY (email_address_id) REFERENCES public.account_emailaddress(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5097 (class 2606 OID 17014)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5098 (class 2606 OID 17009)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5096 (class 2606 OID 17000)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5099 (class 2606 OID 17029)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5100 (class 2606 OID 17024)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5101 (class 2606 OID 17043)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5102 (class 2606 OID 17038)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5103 (class 2606 OID 17065)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5104 (class 2606 OID 17070)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5121 (class 2606 OID 18004)
-- Name: socialaccount_socialtoken socialaccount_social_account_id_951f210e_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_social_account_id_951f210e_fk_socialacc FOREIGN KEY (account_id) REFERENCES public.socialaccount_socialaccount(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5122 (class 2606 OID 18028)
-- Name: socialaccount_socialtoken socialaccount_social_app_id_636a42d7_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_social_app_id_636a42d7_fk_socialacc FOREIGN KEY (app_id) REFERENCES public.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5119 (class 2606 OID 17997)
-- Name: socialaccount_socialapp_sites socialaccount_social_site_id_2579dee5_fk_django_si; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_social_site_id_2579dee5_fk_django_si FOREIGN KEY (site_id) REFERENCES public.django_site(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5120 (class 2606 OID 17992)
-- Name: socialaccount_socialapp_sites socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc FOREIGN KEY (socialapp_id) REFERENCES public.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5118 (class 2606 OID 17984)
-- Name: socialaccount_socialaccount socialaccount_socialaccount_user_id_8146e70c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_user_id_8146e70c_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5109 (class 2606 OID 17808)
-- Name: techspark_address techspark_address_user_id_c1ae140e_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.techspark_address
    ADD CONSTRAINT techspark_address_user_id_c1ae140e_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5106 (class 2606 OID 17141)
-- Name: techspark_cart techspark_cart_user_id_4aba98c2_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.techspark_cart
    ADD CONSTRAINT techspark_cart_user_id_4aba98c2_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5107 (class 2606 OID 17146)
-- Name: techspark_cartitem techspark_cartitem_cart_id_13d90c68_fk_techspark_cart_id; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.techspark_cartitem
    ADD CONSTRAINT techspark_cartitem_cart_id_13d90c68_fk_techspark_cart_id FOREIGN KEY (cart_id) REFERENCES public.techspark_cart(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5108 (class 2606 OID 17151)
-- Name: techspark_cartitem techspark_cartitem_product_id_19fe6174_fk_techspark_product_id; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.techspark_cartitem
    ADD CONSTRAINT techspark_cartitem_product_id_19fe6174_fk_techspark_product_id FOREIGN KEY (product_id) REFERENCES public.techspark_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5110 (class 2606 OID 17814)
-- Name: techspark_order techspark_order_user_id_90dd486a_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.techspark_order
    ADD CONSTRAINT techspark_order_user_id_90dd486a_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5111 (class 2606 OID 17820)
-- Name: techspark_orderitem techspark_orderitem_order_id_5383daf9_fk_techspark_order_id; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.techspark_orderitem
    ADD CONSTRAINT techspark_orderitem_order_id_5383daf9_fk_techspark_order_id FOREIGN KEY (order_id) REFERENCES public.techspark_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5112 (class 2606 OID 17830)
-- Name: techspark_orderitem techspark_orderitem_product_id_3044a3cd_fk_techspark_product_id; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.techspark_orderitem
    ADD CONSTRAINT techspark_orderitem_product_id_3044a3cd_fk_techspark_product_id FOREIGN KEY (product_id) REFERENCES public.techspark_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5105 (class 2606 OID 17758)
-- Name: techspark_product techspark_product_category_id_c43f7c8f_fk_techspark_category_id; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.techspark_product
    ADD CONSTRAINT techspark_product_category_id_c43f7c8f_fk_techspark_category_id FOREIGN KEY (category_id) REFERENCES public.techspark_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5113 (class 2606 OID 17852)
-- Name: techspark_rating techspark_rating_order_item_id_b25ca4ee_fk_techspark; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.techspark_rating
    ADD CONSTRAINT techspark_rating_order_item_id_b25ca4ee_fk_techspark FOREIGN KEY (order_item_id) REFERENCES public.techspark_orderitem(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5114 (class 2606 OID 17857)
-- Name: techspark_rating techspark_rating_product_id_92278286_fk_techspark_product_id; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.techspark_rating
    ADD CONSTRAINT techspark_rating_product_id_92278286_fk_techspark_product_id FOREIGN KEY (product_id) REFERENCES public.techspark_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5115 (class 2606 OID 17862)
-- Name: techspark_rating techspark_rating_user_id_e443a33c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: techspark_user
--

ALTER TABLE ONLY public.techspark_rating
    ADD CONSTRAINT techspark_rating_user_id_e443a33c_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2025-11-10 20:27:25

--
-- PostgreSQL database dump complete
--

\unrestrict xMVffIskuXGB8ouokmH9vm5hE6IDwqRdxUVzAMEfmXsazSDWEe7sg7D97REZtsA

