# Generated by Django 5.2.7 on 2025-11-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techspark', '0006_address_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash On Delivery (COD)'), ('qris', 'QRIS')], default='cod', max_length=10),
        ),
    ]
