# Generated by Django 5.2.7 on 2025-11-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techspark', '0008_order_status_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash On Delivery (COD)'), ('qris', 'QRIS')], default='cod', max_length=10),
        ),
    ]
